<a href="https://colab.research.google.com/github/Shailesh0209/x_Machine_Learning_Practicals-diploma-IITM/blob/main/MLP_Week_1_Programming_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Practice Questions

Question Group Name: 22T1_MLP_W1_PP

Total No. of Ques: 6

**Question 1**


Which of the following options are the class names in the iris dataset?

(a) ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

(b) ['setosa' 'versicolor' 'virginica']

(c) ['setosa' 'virginica']

(d) ['sepal length (cm)', 'petal length (cm)', 'petal width (cm)']

**Correct Answer: Option 2**                                                     
(1 marks)


In [ ]:
from sklearn.datasets import load_iris
data = load_iris()
print(data.feature_names)
print(data.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


**Question 2**

Generate 200 samples with 10 features for multiple regression problem with 10 outputs and find the shapes of the feature matrix and the label vector.

(a) Feature matrix shape: (200,10), label vector shape: (200,10)

(b) Feature matrix shape: (10,200), label vector shape: (10,200)

(c) Feature matrix shape: (200,200), label vector shape: (10,10)

(d) Feature matrix shape: (10,10), label vector shape: (200,200)

**Correct Answer: Option 1**     

(1 Marks)


**Solution**

In [ ]:
from sklearn.datasets import make_regression
#?make_regression  
x, y = make_regression(n_samples=200, n_features=10, n_targets=10, shuffle=True)
print(x.shape)
print(y.shape)

(200, 10)
(200, 10)




**Question 3**

Find the shapes of the feature matrix and the label vector for a  multilabel classification problem with 200 samples, 10 features, 7 labels and on an average 3 labels per example.

(a) Feature matrix: (200,10), Label vector: (200,7)

(b) Feature matrix: (200,200), Label vector: (10,7)

(c) Feature matrix: (200,7), Label vector: (200,10)

(d)Feature matrix: (199,9), Label vector: (199,6)

**Correct Answer: Option 1**     

(1 Marks)

**Solution**

In [ ]:
from sklearn.datasets import make_multilabel_classification
x, y = make_multilabel_classification(n_samples=200, n_features=10, n_classes=7, n_labels=3)
print(x.shape)
print(y.shape)
print(x[:10])
print(y[:10])

(200, 10)
(200, 7)
[[ 1.  3.  5.  1. 14.  1. 10.  5.  1.  2.]
 [ 2.  6.  3.  0.  3.  8.  3.  7.  4.  4.]
 [ 4. 12.  0.  4.  6.  6.  5.  6.  2.  9.]
 [ 7.  5.  0.  2.  5.  1.  5.  5.  0.  4.]
 [ 4.  2. 10.  1.  5.  3.  9.  9.  3.  2.]
 [ 6.  5.  4.  4.  4.  3.  2.  4.  0.  5.]
 [ 2. 10.  9.  1. 10.  0.  9.  3.  3.  5.]
 [ 1.  8.  0.  1. 12.  2. 13.  7.  2.  3.]
 [ 3. 14.  6.  7.  7.  2.  8.  7.  1.  6.]
 [ 3.  7.  5.  1. 13.  2.  6.  6.  0.  3.]]
[[0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 1 0 0 0]
 [0 1 1 0 1 0 0]
 [0 0 0 0 1 0 1]
 [1 1 1 1 0 1 1]
 [0 0 0 0 1 0 1]
 [0 0 0 0 1 0 0]
 [1 0 1 0 1 0 0]
 [1 0 0 0 1 0 0]]


**Question 4**

Which of the following functions can be used to load the [diabetes](https://archive.ics.uci.edu/ml/datasets/Diabetes) dataset as a dataframe?

(a) x,y= load_diabetes(as_frame=True,return_X_y=True)

(b)x,y= load_diabetes(as_frame=True,return_X_y=False)

(c) print(load('diabetes'))

(d) load diabetes_frame

**Correct Answer: Option 1**     

(1 Mark)

**Question 5**

What are the datatypes of the feature matrix and the target matrix in the diabetes dataset (by using `load_diabetes()` from `sklearn`)?

(a) DataFrame and Series

(b) Series and DataFrame

(c) Both are Series

(d) Both are DataFrames

**Correct Answer: Option 1**

(1 Marks)

**Solution**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.datasets import load_diabetes
x,y= load_diabetes(as_frame=True,return_X_y=True)#x is the feature matrix, y is target matrix
# return_X_ybool, default=False. If True, returns (data, target) instead of a Bunch object. See below for more information about the data and target object.
data=x+y


In [ ]:
print(type(x)) #PRINT THE DATATYPE OF FEATURE MATRIX
print(type(y))#print the datatype of the target matrix
print(type(data))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


**Question 6**:  Which of the following options can be the output of the following code?




In [ ]:
#codeblock
from sklearn.datasets import make_blobs
X, y = make_blobs(n_samples=10, centers=3, n_features=2, random_state=42)
print ("Feature matrix shape:", X.shape)

(a) Feature matrix shape: (10, 2)

(b) Feature matrix shape: (2, 10)

(c) Feature matrix shape: (10, 10)

(d) Feature matrix shape: (2, 2)

**Correct Answer: Option 1**

(2 Marks)

**Solution**

In [ ]:
from sklearn.datasets import make_blobs
X, y = make_blobs(n_samples=10, centers=3, n_features=2, random_state=42)
print ("Feature matrix shape:", X.shape)
#print ("Label shape:", y.shape)
plt.scatter(X[:0],X[:,1])

Feature matrix shape: (10, 2)


In [ ]:

X, y = make_blobs(n_samples=10, centers=3, n_features=2, random_state=42)
print ("Feature matrix shape:", X.shape)
print ("Label shape:", y.shape)

Feature matrix shape: (10, 2)
Label shape: (10,)


#Graded Questions

Question Group Name: 22T1_MLP_W1_PG

Total No. of Ques: 6

**Question 1**

Find shape of the Wisconsin breast cancer dataset (https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Original)).

(a)(570, 35)

(b) (569, 33)

(c) (33,569)

(d) (35,570)

**Correct Answer: Option 2**

(2 Marks)

**Question 2**

How many benign ($B$) tumour cases are present in the Wisconsin breast cancer dataset (https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Original))?

(**NAT Question**)

**Correct Answer: 357**

(2 Marks)



**Question 3**

How many malignant ($M$) tumour cases are present in the Wisconsin breast cancer dataset (https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Original)).?

(**NAT Question**)

**Correct Answer: 212**

(2 Marks)

**Solution**

In [ ]:
import pandas as pd
import numpy as np
import pandas_profiling
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_csv('/content/data.csv')
data.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
print(data.shape)#print the shape of the data

(569, 33)


In [ ]:
data.describe()

id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
count  5.690000e+02   569.000000  ...               569.000000          0.0
mean   3.037183e+07    14.127292  ...                 0.083946          NaN
std    1.250206e+08     3.524049  ...                 0.018061          NaN
min    8.670000e+03     6.981000  ...                 0.055040          NaN
25%    8.692180e+05    11.700000  ...                 0.071460          NaN
50%    9.060240e+05    13.370000  ...                 0.080040          NaN
75%    8.813129e+06    15.780000  ...                 0.092080          NaN
max    9.113205e+08    28.110000  ...                 0.207500          NaN

[8 rows x 32 columns]

In [ ]:
data.groupby('diagnosis').describe()

id                                      ... Unnamed: 32            
           count          mean           std     min  ...         25% 50% 75% max
diagnosis                                             ...                        
B          357.0  2.654382e+07  1.167397e+08  8913.0  ...         NaN NaN NaN NaN
M          212.0  3.681805e+07  1.378965e+08  8670.0  ...         NaN NaN NaN NaN

[2 rows x 256 columns]

In [ ]:
data.diagnosis.hist()
plt.xlabel('Diagnosis')
plt.ylabel('Count')

In [ ]:
data.hist(bins=50,figsize=(15,15))
# display histogram
plt.show()

**Instructions for Questions 4-6**: Use the following code for importing California Housing dataset from sklearn. Also, name the dataset as housing_data and print description of the dataset.

In [ ]:
#codeblock
from sklearn.datasets import fetch_california_housing
housing_data = fetch_california_housing()
print(housing_data.DESCR)

**Solution**

**Question 4**: Find out the shape of the feature matrix in california housing dataset.

(a) (20118,19)

(b) (20640, 8)

(c) (8, 8)

(d) (8, 20640)

**Correct Answer: Option 2**

(1 Marks)

In [ ]:
print(housing_data.data.shape)
#print(housing_data.data[:5])

(20640, 8)


**Question 5**: Find out the labels of the first five attributes in california housing dataset. Note, the labels are real-valued.

(a) [4.526, 3.413, 3.422, 1.22, 6.02]

(b) [4.526, 3.585, 3.521, 3.413, 3.422]

(c) [3.413, 3.422, 4.526, 3.585, 1.249]

(d) [4.526, 502.0, 3.521, 3.413, 1025.5]

**Correct Answer: Option 2**

(1.5 Marks)



**Solution**

In [ ]:
print(housing_data.target.shape)
print(housing_data.target[:5])

(20640,)
[4.526 3.585 3.521 3.413 3.422]


**Question 6**: Find out the name of the class label in california housing dataset(target matrix)?

(a)['MedHouseVal']

(b) ['MedInc']

(c) ['AveRooms']

(d) ['Population']

**Correct Answer: Option 1**

(1 Marks)

**Solution**

In [ ]:
print(housing_data.feature_names)
print(housing_data.target_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
['MedHouseVal']
